/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MintRouteImport } from './routes/mint'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DexRouteImport } from './routes/dex'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as DexIndexRouteImport } from './routes/dex.index'
import { Route as UAddressRouteImport } from './routes/u.$address'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as DexSwapRouteImport } from './routes/dex.swap'
import { Route as DexLiquidityRouteImport } from './routes/dex.liquidity'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MintRoute = MintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DexRoute = DexRouteImport.update({
  id: '/dex',
  path: '/dex',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const DexIndexRoute = DexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DexRoute,
} as any)
const UAddressRoute = UAddressRouteImport.update({
  id: '/u/$address',
  path: '/u/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DexSwapRoute = DexSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => DexRoute,
} as any)
const DexLiquidityRoute = DexLiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => DexRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/dex': typeof DexRouteWithChildren
  '/docs': typeof DocsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mint': typeof MintRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dex/liquidity': typeof DexLiquidityRoute
  '/dex/swap': typeof DexSwapRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/u/$address': typeof UAddressRoute
  '/dex/': typeof DexIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/docs': typeof DocsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mint': typeof MintRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dex/liquidity': typeof DexLiquidityRoute
  '/dex/swap': typeof DexSwapRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/u/$address': typeof UAddressRoute
  '/dex': typeof DexIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/dex': typeof DexRouteWithChildren
  '/docs': typeof DocsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mint': typeof MintRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dex/liquidity': typeof DexLiquidityRoute
  '/dex/swap': typeof DexSwapRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/u/$address': typeof UAddressRoute
  '/dex/': typeof DexIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/dex'
    | '/docs'
    | '/leaderboard'
    | '/mint'
    | '/profile'
    | '/sitemap.xml'
    | '/dex/liquidity'
    | '/dex/swap'
    | '/marketplace/$id'
    | '/u/$address'
    | '/dex/'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/docs'
    | '/leaderboard'
    | '/mint'
    | '/profile'
    | '/sitemap.xml'
    | '/dex/liquidity'
    | '/dex/swap'
    | '/marketplace/$id'
    | '/u/$address'
    | '/dex'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/dex'
    | '/docs'
    | '/leaderboard'
    | '/mint'
    | '/profile'
    | '/sitemap.xml'
    | '/dex/liquidity'
    | '/dex/swap'
    | '/marketplace/$id'
    | '/u/$address'
    | '/dex/'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DexRoute: typeof DexRouteWithChildren
  DocsRoute: typeof DocsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MintRoute: typeof MintRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  UAddressRoute: typeof UAddressRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint': {
      id: '/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex': {
      id: '/dex'
      path: '/dex'
      fullPath: '/dex'
      preLoaderRoute: typeof DexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex/': {
      id: '/dex/'
      path: '/'
      fullPath: '/dex/'
      preLoaderRoute: typeof DexIndexRouteImport
      parentRoute: typeof DexRoute
    }
    '/u/$address': {
      id: '/u/$address'
      path: '/u/$address'
      fullPath: '/u/$address'
      preLoaderRoute: typeof UAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex/swap': {
      id: '/dex/swap'
      path: '/swap'
      fullPath: '/dex/swap'
      preLoaderRoute: typeof DexSwapRouteImport
      parentRoute: typeof DexRoute
    }
    '/dex/liquidity': {
      id: '/dex/liquidity'
      path: '/liquidity'
      fullPath: '/dex/liquidity'
      preLoaderRoute: typeof DexLiquidityRouteImport
      parentRoute: typeof DexRoute
    }
  }
}

interface DexRouteChildren {
  DexLiquidityRoute: typeof DexLiquidityRoute
  DexSwapRoute: typeof DexSwapRoute
  DexIndexRoute: typeof DexIndexRoute
}

const DexRouteChildren: DexRouteChildren = {
  DexLiquidityRoute: DexLiquidityRoute,
  DexSwapRoute: DexSwapRoute,
  DexIndexRoute: DexIndexRoute,
}

const DexRouteWithChildren = DexRoute._addFileChildren(DexRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  DexRoute: DexRouteWithChildren,
  DocsRoute: DocsRoute,
  LeaderboardRoute: LeaderboardRoute,
  MintRoute: MintRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  UAddressRoute: UAddressRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
